import { z } from "zod";

export const clientFormSchema = z.object({
  profile_picture: z.string().optional(),
  title: z.string(),
  first_name: z.string(),
  last_name: z.string(),
  gender: z.string(),
  dob: z.string(),
  marital_status: z.string(),
  status: z.string(),
  email: z.string().email().optional(),
  phone: z.string(),
  weight: z.number(),
  height: z.number(),
  address: z.string(),
  visit_frequency: z.string(),
  service_type: z.string(),
  care_plan: z.string().optional(),
  social_worker_first_name: z.string().optional(),
  social_worker_last_name: z.string().optional(),
  social_worker_email: z.string().email().optional(),
  social_worker_phone: z.string().optional(),
  social_worker_schedule: z.string().optional(),
  social_worker_visit_frequency: z.string().optional(),
  emergency_contact: z.object({
    first_name: z.string(),
    last_name: z.string(),
    relationship: z.string(),
    email: z.string().email().optional(),
    phone: z.string(),
    address: z.string(),
  }),
  family_members: z.array(z.object({
    first_name: z.string(),
    last_name: z.string(),
    relationship: z.string(),
    gender: z.string(),
    email: z.string().email().optional(),
    phone: z.string(),
    address: z.string(),
    has_access: z.boolean().default(true),
  })),
  medical_condition: z.object({
    conditions: z.array(z.string()),
    summary: z.string().optional(),
  }),
  allergy: z.array(z.object({
    common_name: z.string().optional(),
    allergen: z.string(),
    severity: z.enum(["mild", "moderate", "severe"]),
    notes: z.string().optional(),
  })),
  medication: z.array(z.object({
    name: z.string(),
    dosage: z.string(),
    frequency: z.string(),
    start_date: z.string(),
    end_date: z.string().optional(),
    notes: z.string().optional(),
  })),
  medical_visits: z.array(z.object({
    date: z.string(),
    doctor_name: z.string(),
    reason: z.string(),
    notes: z.string().optional(),
  })),
  client_documents: z.array(z.object({
    name: z.string(),
    url: z.string(),
  })),
});

export type ClientFormData = z.infer<typeof clientFormSchema>;
